= Asciidoctor Extensions
:doctype: book

Plenty of extensions to play with at https://github.com/asciidoctor/asciidoctor-extensions-lab

== Emoji Inline Extension (emoji-inline-macro.rb)
// must pass allow-uri-read to enable data-uri behavior, see in the pom.xml attributes
:data-uri:
:cache-uri:

Faster than a emoji:turtle[1x]!

This is an example of how you can emoji:heart[lg] Asciidoctor and Twitter Emoji.

== Gist Block Extension (gist-block-macro.rb)

.Guard setup to live preview AsciiDoc output
gist::mojavelinux/5546622[]

== Lorem Extension (lorem-block-macro.rb)

This requires middleman >= 4.0.0 (`gem install middleman`).

lorem::sentences[5]

= Shell Session Extension (shell-session-treeprocessor.rb)

 $ echo 'Hello, World!'
 > Hello, World!

 $ gem install asciidoctor

= Tree Block Macro Extension (tree-block-macro.rb)
:icons: font

Here's what's in the directory:

.Contents of lib folder in Asciidoctor gem
tree::{user-home}/Documents/Code/Agoncal/agoncal-other/02-AsciidocExtensions/[]

== Dita Diagram

[ditaa,asciidoctor-diagram-process]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        |---+ Asciidoctor +--->|               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....


== PlantUML Diagram

[plantuml,auth-protocol]
....
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
....
