= Configuring the AsciiDoctor Maven Plugin
:doctype: book
:imagesdir: images

Plenty of extensions to play with at https://github.com/asciidoctor/asciidoctor-extensions-lab

== Using include with a remote file
// must pass allow-uri-read to enable data-uri behavior, see in the pom.xml attributes

[source]
----
include::https://raw.githubusercontent.com/agoncal/agoncal-book-javaee7/master/chapter03/chapter03-samples/src/main/java/org/agoncal/book/javaee7/chapter03/ex01/Book01.java[tag=snippets]
----

== Emoji Inline Extension (emoji-inline-macro.rb)

I trully emoji:heart[lg] my little green emoji:turtle[1x]!

== Gist Block Extension (gist-block-macro.rb)

.Guard setup to live preview AsciiDoc output
gist::mojavelinux/5546622[]

== Lorem Extension (lorem-block-macro.rb)

This requires middleman >= 4.0.0

lorem::sentences[5]

== Shell Session Extension (shell-session-treeprocessor.rb)

 $ echo 'Hello, World!'
 > Hello, World!

 $ gem install asciidoctor

== Tree Block Macro Extension (tree-block-macro.rb)
// Uses the Fontawesome icons
:icons: font

Here's what's in the directory:

.Contents of the directory
tree::{user-home}/Documents/Code/Agoncal/agoncal-other/02-AsciidocExtensions/src/main[]

== Dita Diagram

[ditaa,asciidoctor-diagram-process]
....
                   +-------------+
                   | Asciidoctor |-------+
                   |   diagram   |       |
                   +-------------+       | PNG out
                       ^                 |
                       | ditaa in        |
                       |                 v
 +--------+   +--------+----+    /---------------\
 |        |---+ Asciidoctor +--->|               |
 |  Text  |   +-------------+    |   Beautiful   |
 |Document|   |   !magic!   |    |    Output     |
 |     {d}|   |             |    |               |
 +---+----+   +-------------+    \---------------/
     :                                   ^
     |          Lots of work             |
     +-----------------------------------+
....


== PlantUML Diagram

[plantuml,auth-protocol]
....
Alice -> Bob: Authentication Request
Bob --> Alice: Authentication Response

Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
....
